### ISSUE TITLE
Controller issue : dynamic provisioning

### ISSUE THREAD

**Issue by pgasca** [kubernetes-sigs/aws-efs-csi-driver#555] opened 2021-09-15 15:11 UTC
Moving this from awsdocs/amazon-eks-user-guide [issue #426](https://github.com/awsdocs/amazon-eks-user-guide/issues/426) as suggested by [tyler-bixal](https://github.com/tyler-bixal).

From [tontondematt](https://github.com/tontondematt):
"Hello, 

I am trying to setup efs using the aws official csi driver. (I am currently using the efs provisionner and it's working just fine)
I followed the user guide to the letter as descibed in here https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html
checked, double checked and triple checked.

I am having an issue with the csi controller : 
when i try to create a PVC which points to my storage class which it self points the my efs , i am faced with this error and have no way to find what's going on as the logs don't say too much : 

`I0804 16:27:47.294125       1 controller.go:58] CreateVolume: called with args {Name:pvc-81004c2c-d6ba-42c3-86f7-44c08e47e991 CapacityRange:required_bytes:5368709120  VolumeCapabilities:[mount:<> access_mode: ] Parameters:map[csi.storage.k8s.io/pv/name:pvc-81004c2c-d6ba-42c3-86f7-44c08e47e991 csi.storage.k8s.io/pvc/name:efs-claim csi.storage.k8s.io/pvc/namespace:kube-system directoryPerms:700 fileSystemId:fs-bef87c8a gidRangeEnd:2000 gidRangeStart:1000 provisioningMode:efs-ap] Secrets:map[] VolumeContentSource: AccessibilityRequirements: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0804 16:27:47.294289       1 cloud.go:218] Calling DescribeFileSystems with input: {
  FileSystemId: "fs-bef87c8a"
}
E0804 16:27:57.293533       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to fetch File System info: Describe File System failed: RequestCanceled: request context canceled
caused by: context deadline exceeded`

Reading this would suggest that my service account doesn't have the permissions to do a describe file system , but it should combining these : 
`
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::XXXXXXXXXXXXXXXXXXXX:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXX"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.eu-west-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXX:sub": "system:serviceaccount:kube-system:efs-csi-controller-sa"
        }
      }`

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:DescribeAccessPoints",
        "elasticfilesystem:DescribeFileSystems"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:CreateAccessPoint"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "aws:RequestTag/efs.csi.aws.com/cluster": "true"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": "elasticfilesystem:DeleteAccessPoint",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/efs.csi.aws.com/cluster": "true"
        }
      }
    }
  ]
`

My test pod is running on an eks cluster inside a vpc.
I can provide more infos if needed."

From [tyler-bixal](https://github.com/tyler-bixal):
"I can recreate this issue. I'd like to point out that it only occurs with dynamic provisioning and static provisioning can still be used. [The EFS CSI Driver project](https://github.com/kubernetes-sigs/aws-efs-csi-driver) might be a more appropriate place to report this type of issue as it seems like a bug in the driver itself."

**Comment by kbasv** [comment] 2021-09-15 15:38
@pgasca / @tontondematt / @tyler-bixal

1. Is your file system's life-cycle in `available` state at the time of dynamic provisioning?
2. Is your EKS cluster running in private VPC?

**Comment by tyler-bixal** [comment] 2021-09-15 15:42
> @pgasca / @tontondematt / @tyler-bixal
> 
>     1. Is your file system's life-cycle in `available` state at the time of dynamic provisioning?
> 
>     2. Is your EKS cluster running in private VPC?

1. Yes, I am able to statically provision persistent volumes then directly after, not be able to dynamically provision.
2. The subnets where my EKS cluster lives are private but the VPC itself is public with a functional internet gateway and public subnets.

**Comment by kbasv** [comment] 2021-09-16 16:20
@tyler-bixal 

Can you check if you are able to call efs api using `aws` commands from your EKS cluster. For example, you can run describe file systems call using the following command - `aws efs describe-file-systems`

**Comment by tyler-bixal** [comment] 2021-09-17 19:38
> @tyler-bixal
> 
> Can you check if you are able to call efs api using `aws` commands from your EKS cluster. For example, you can run describe file systems call using the following command - `aws efs describe-file-systems`

I created a pod using the same service account that I gave to the EFS CSI driver, used the credentials given to the pod and was able to identify an issue with the IRSA configuration in use by the pod. Correcting that, dynamic provisioning now works as intended in my cluster. 

You can count my part of this resolved but I cannot speak for @tontondematt and the original issue. Thank you for your time @kbasv and I apologize for the mistake on my part.

**Comment by tontondematt** [comment] 2021-09-26 19:10
wow thanks guys, i had lost hope in any response. I will try your suggestions and come back to you asap .

**Comment by holmesb** [comment] 2021-11-18 14:29
Error "Failed to fetch File System info: Describe File System failed" when trying to provision dynamically on private EKS is fixed by my PR #585 that I submitted a week ago.  Be great if someone could review\merge.

**Comment by mfbieber** [comment] 2021-12-02 18:13
I believe we have the same issues with a private cluster. We would appreciate that fix a lot 😍

**Closed** 2022-05-01 19:51 UTC
Labels: lifecycle/rotten

**Comment by vsivas** [comment] 2024-03-28 06:23
Hi @holmesb 
 In my case its same error but I am using EFS CSI Driver. 
I have done as per: https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/
Any suggestions please

errors in EFS Controller logs : 
—————————————————————————————
I0326 09:06:06.820914 1 controller.go:1082] Temporary error received, adding PVC 3f096f7a-9b79-4ad5-bd1c-992c66b73069 to claims in progress 
W0326 09:06:06.820948 1 controller.go:934] Retrying syncing claim "3f096f7a-9b79-4ad5-bd1c-992c66b73069", failure 67 
E0326 09:06:06.820968 1 controller.go:957] error syncing claim "3f096f7a-9b79-4ad5-bd1c-992c66b73069": failed to provision volume with StorageClass "aws-efs-csi-sc-cevoc-dev": rpc error: code = DeadlineExceeded desc = context deadline exceeded 
I0326 09:06:06.820994 1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cevoc-1-dev", Name:"efs-claim", UID:"3f096f7a-9b79-4ad5-bd1c-992c66b73069", APIVersion:"v1", ResourceVersion:"119237073", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "aws-efs-csi-sc-cevoc-dev": rpc error: code = DeadlineExceeded desc = context deadline exceeded
