### ISSUE TITLE
Provider support to pass custom labels to the Helm Chart

### ISSUE THREAD

**Issue by rajramo61** [kubernetes-sigs/aws-efs-csi-driver#1240] opened 2024-01-11 02:58 UTC
**Is your feature request related to a problem?/Why is this needed**
[aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) helm chart does not support custom labels. These metadata properties can provide some very useful information for the teams who use it. 

/feature

**Describe the solution you'd like in detail**
Provide and option for passing commonLabel from values.yaml to the resources. 

**Describe alternatives you've considered**
Other than chart name which is used as selector, there is no other way to pass custom labels to the chart.
Without making changes to helm chart, use kustomize to add labels as postRenderer or need to write mutating webhook in cluster to add the custom labels. But if we have option in helm chart itself then it makes this process very easy.

**Additional context**
aws-ebs-csi-driver helm chart provides this option. [Here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L12C1-L12C13) is the reference.

**Comment by den-pluto** [comment] 2024-01-16 14:48
That's duplicate of earlier https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1237

**Comment by rajramo61** [comment] 2024-01-17 16:48
Thanks @den-pluto . But this PR is different as it adds labels to deployments and service account as well. But the other PR adds labels to pods and nodes. So they share some common resources but not the same. This PR cover more resources that #1237 .

**Comment by seanzatzdev-amazon** [comment] 2024-04-19 18:49
Hi @rajramo61 , I see you mentioned a PR you created in your previous comments (https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1240#issuecomment-1896204092). Can you please add a link to your PR or open it against our repo if you have not already?

**Comment by seanzatzdev-amazon** [comment] 2024-04-19 19:52
@rajramo61 Thank you for your PR, we will work on reviewing the changes

**Closed** 2024-06-18 20:14 UTC
Labels: lifecycle/rotten
