### ISSUE TITLE
Support node start-up taint to avoid race conditions

### ISSUE THREAD

**Issue by RyanStan** [kubernetes-sigs/aws-efs-csi-driver#1069] opened 2023-07-17 23:18 UTC
**Is your feature request related to a problem? Please describe.**
In some cases when new nodes frequently join the cluster, workloads (application Pods) which require EFS volumes can be scheduled to a new EC2 Node before the efs-csi-node Pod has finished initialization and is ready on that Node. This race condition between workload pod and efs-csi-node Pod will cause the workload Pod to fail mounting the PVC.

We should apply a startup taint to prevent this race condition from occurring. The efs-csi-node Daemonset's efs-plugin container will apply this taint to the Node during driver initialization, and then will remove the taint once it is ready.

**Describe the solution you'd like in detail**
See the following PR on aws-ebs-csi-driver which implements this feature: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1581

From the overview of that PR:
> This PR added support for start-up taint removal for csi-node daemonset pods. This feature allows cluster admin to set taints on nodes, blocking workload pod to be scheduled before the driver start up and be ready. By automatically remove the taints marks the node ready for any CSI functionalities and workload start to be scheduled to the node. This feature can be configured in driver options and in Helm values.

**Comment by allamand** [comment] 2023-10-06 07:38
The related Fix on EBS is : https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1588

**Comment by jumasa** [comment] 2023-10-20 07:43
I believe I'm encountering a similar issue. I can consistently reproduce it when the Horizontal Pod Autoscaler initiates a scale-up due to load metrics (the are pods receiving traffic). 
However, when I manually scale up the deployment without any incoming traffic to the pods, and wait for all pods to become operational before sending traffic to them, the issue doesn't manifest.

**Comment by OverStruck** [comment] 2023-11-08 19:13
team please look into this

**Comment by mskanth972** [comment] 2023-11-14 21:10
Our team has acknowledged this issue and it's currently on our priority list. We are actively working it and aim to have this resolved and released by the end of this month.

**Comment by mskanth972** [comment] 2023-11-17 21:02
[PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1197)  for this feature. Will merge this and release in the coming version, most probably by end of this month.

**Comment by mskanth972** [comment] 2024-01-08 03:47
[PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1197) addressing the feature request for supporting node start-up taint to avoid race conditions has been successfully merged. This feature is now included in the EFS CSI Driver as of version v1.7.2.

**Closed by mskanth972** 2024-01-08 03:47 UTC
Labels: kind/feature
