### ISSUE TITLE
Provisioning a new PVC causes a segmentation fault in v1.7.0

### ISSUE THREAD

**Issue by nielsmdt** [kubernetes-sigs/aws-efs-csi-driver#1173] opened 2023-10-31 09:29 UTC
/kind bug

**What happened?**
After upgrading the EFS CSI driver to v1.7.0 (Helm chart 2.5.0) we notice creating a new PVC causes a segmentation fault.

```
csi-provisioner I1031 08:53:07.504133       1 controller.go:1359] provision "kuttl-test-equal-chigger/test-csi-efs" class "efs-sc": started
csi-provisioner I1031 08:53:07.540648       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kuttl-test-equal-chigger", Name:"test-csi-efs", UID:"0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb", APIVersion:"v1", ResourceVersion:"6258606", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kuttl-test-equal-chigger/test-csi-efs"
efs-plugin panic: runtime error: invalid memory address or nil pointer dereference
efs-plugin [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16220e6]
efs-plugin 
efs-plugin goroutine 85 [running]:
efs-plugin github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud.(*cloud).ListAccessPoints(0xc000680120, {0x1e5e9b0, 0xc0001ec390}, {0xc00004a360, 0x14})
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud/cloud.go:317 +0x2e6
efs-plugin github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getUsedGids(0x7d0?, {0x1e5e9b0?, 0xc0001ec390?}, {0xc00004a360, 0x14})
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:66 +0x53
efs-plugin github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getNextGid(0xc0001f87e8, {0x1e5e9b0, 0xc0001ec390}, {0xc00004a360, 0x14}, 0x1e708d0?, 0x19cf700?)
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:42 +0x1fe
efs-plugin github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).CreateVolume(0xc0001f8750, {0x1e5e9b0, 0xc0001ec390}, 0xc0005b8690)
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/controller.go:257 +0x14fe
efs-plugin github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x1e5e9b0, 0xc0001ec390}, {0x19cb100?, 0xc0005b8690})
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x78
efs-plugin github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).Run.func1({0x1e5e9b0?, 0xc0001ec390?}, {0x19cb100?, 0xc0005b8690?}, 0xc0005d5a50?, 0x1861ee0?)
csi-provisioner I1031 08:53:07.870061       1 controller.go:1082] Temporary error received, adding PVC 0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb to claims in progress
csi-provisioner W1031 08:53:07.870078       1 controller.go:934] Retrying syncing claim "0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb", failure 0
csi-provisioner E1031 08:53:07.870092       1 controller.go:957] error syncing claim "0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb": failed to provision volume with StorageClass "efs-sc": rpc error: code = Unavailable desc = error reading from server: EOF
csi-provisioner I1031 08:53:07.870147       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kuttl-test-equal-chigger", Name:"test-csi-efs", UID:"0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb", APIVersion:"v1", ResourceVersion:"6258606", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "efs-sc": rpc error: code = Unavailable desc = error reading from server: EOF
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/driver.go:101 +0x42
efs-plugin github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x1a31640?, 0xc0001f8750}, {0x1e5e9b0, 0xc0001ec390}, 0xc0005b8620, 0x1b7c558)
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5680 +0x138
efs-plugin google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e4000, {0x1e644e0, 0xc000007ba0}, 0xc00045bc20, 0xc0004f4de0, 0x2aecc40, 0x0)
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1336 +0xd33
efs-plugin google.golang.org/grpc.(*Server).handleStream(0xc0001e4000, {0x1e644e0, 0xc000007ba0}, 0xc00045bc20, 0x0)
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1704 +0xa36
efs-plugin google.golang.org/grpc.(*Server).serveStreams.func1.2()
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:965 +0x98
efs-plugin created by google.golang.org/grpc.(*Server).serveStreams.func1
efs-plugin     /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:963 +0x28a
csi-provisioner I1031 08:53:08.870847       1 controller.go:1359] provision "kuttl-test-equal-chigger/test-csi-efs" class "efs-sc": started
csi-provisioner E1031 08:53:08.870988       1 connection.go:142] Lost connection to unix:///var/lib/csi/sockets/pluginproxy/csi.sock.
csi-provisioner I1031 08:53:08.871000       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kuttl-test-equal-chigger", Name:"test-csi-efs", UID:"0ddbaba5-358e-4cf6-ae49-c8f3a4bb6cfb", APIVersion:"v1", ResourceVersion:"6258606", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kuttl-test-equal-chigger/test-csi-efs"
csi-provisioner F1031 08:53:08.871126       1 connection.go:97] Lost connection to CSI driver, exiting
Stream closed EOF for kube-system/efs-csi-controller-77994d7f59-j8pg4 (efs-plugin)
```

**What you expected to happen?**
v1.6.0:
```
csi-provisioner I1031 08:51:31.503685       1 controller.go:1359] provision "kuttl-test-major-ghoul/test-csi-efs" class "efs-sc": started
csi-provisioner I1031 08:51:31.503872       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kuttl-test-major-ghoul", Name:"test-csi-efs", UID:"5bb32ee8-40ad-4d06-8013-5c62619cfe9e", APIVersion:"v1", ResourceVersion:"6257578", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kuttl-test-major-ghoul/test-csi-efs"
csi-provisioner I1031 08:51:31.672854       1 controller.go:923] successfully created PV pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e for PVC test-csi-efs and csi volume name fs-0b2e7a7880eb2a60e::fsap-02b92ca52a07a8102
csi-provisioner I1031 08:51:31.672888       1 controller.go:1442] provision "kuttl-test-major-ghoul/test-csi-efs" class "efs-sc": volume "pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e" provisioned
csi-provisioner I1031 08:51:31.672901       1 controller.go:1455] provision "kuttl-test-major-ghoul/test-csi-efs" class "efs-sc": succeeded
csi-provisioner I1031 08:51:31.681799       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kuttl-test-major-ghoul", Name:"test-csi-efs", UID:"5bb32ee8-40ad-4d06-8013-5c62619cfe9e", APIVersion:"v1", ResourceVersion:"6257578", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e
csi-provisioner I1031 08:51:41.349999       1 controller.go:1502] delete "pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e": started
csi-provisioner I1031 08:51:41.350037       1 controller.go:1279] volume pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e does not need any deletion secrets
csi-provisioner I1031 08:51:41.391182       1 controller.go:1517] delete "pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e": volume deleted
csi-provisioner I1031 08:51:41.400548       1 controller.go:1562] delete "pvc-5bb32ee8-40ad-4d06-8013-5c62619cfe9e": persistentvolume deleted succeeded
```

**How to reproduce it (as minimally and precisely as possible)?**
Create a PVC and a Deployment that mounts it.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.26.9-eks-f8587cb
- Driver version: 1.7.0

**Please also attach debug logs to help us better diagnose**

[driver_info.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13214521/driver_info.txt)
[driver_logs.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13214522/driver_logs.txt)

**Comment by franckdrion** [comment] 2023-10-31 13:42
I'm facing the same issue for the past 3 days. 
My helm chart was on version 2.2.6, so 1.3.8 for the CSI Driver. 
I've upgraded the chart incrementally, but the result remains the same, even in version 1.6.0 of the chart which seems to work for you. 

Any help would be appreciated.

**Comment by franckdrion** [comment] 2023-11-03 12:43
Hello @nielsmdt 
after more investiguation I've found that my AWS policy was missing a statement. 
I use the eks blueprint module for terraform and this MR seems to correct the missing statement : https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1573

If you want to check your policy here's what is should looks like : https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json

hope it helps !

**Comment by nielsmdt** [comment] 2023-11-03 15:01
I compared my policy document to the one from here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.7/docs/iam-policy-example.json

Comparing that to mine, I notice the condition is different:
aws-efs-csi-driver project: `aws:ResourceTag/efs.csi.aws.com/cluster`
mine: `aws:RequestTag/efs.csi.aws.com/cluster`

I've updated our role to match the one documented in the aws-efs-csi-driver project, but it doesn't work with v1.7, while v1.6 works as expected.

**Comment by bribroder** [comment] 2023-11-07 18:37
I have the same issue with 1.7.0 which did not occur in 1.6.0. Mine is specific to dynamically provisioned volumes. My IAM policy is an exact match for the example in [1.7](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.7/docs/iam-policy-example.json) (which by the way is not different from 1.6). When I try to create a dynamically provisioned volume, the csi controllers start to crash

```
I1107 18:33:07.883832       1 driver.go:113] Registering Node Server
I1107 18:33:36.895959       1 config_dir.go:63] Mounted directories do not exist, creating directory at '/etc/amazon/efs'
I1107 18:33:36.896424       1 metadata.go:63] getting MetadataService...
I1107 18:33:36.897756       1 metadata.go:68] retrieving metadata from EC2 metadata service
I1107 18:33:36.901492       1 driver.go:140] Did not find any input tags.
I1107 18:33:36.901646       1 driver.go:113] Registering Node Server
I1107 18:33:36.901656       1 driver.go:115] Registering Controller Server
I1107 18:33:36.901664       1 driver.go:118] Starting efs-utils watchdog
I1107 18:33:36.901716       1 efs_watch_dog.go:216] Copying /etc/amazon/efs/efs-utils.conf since it doesn't exist
I1107 18:33:36.901770       1 efs_watch_dog.go:216] Copying /etc/amazon/efs/efs-utils.crt since it doesn't exist
I1107 18:33:36.902776       1 driver.go:124] Starting reaper
I1107 18:33:36.902948       1 driver.go:127] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginproxy/csi.sock", Net:"unix"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16220e6]

goroutine 51 [running]:
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud.(*cloud).ListAccessPoints(0xc0000b6e80, {0x1e5e9b0, 0xc0006a9350}, {0xc0004469e0, 0xb})
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud/cloud.go:317 +0x2e6
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getUsedGids(0x6acfc0?, {0x1e5e9b0?, 0xc0006a9350?}, {0xc0004469e0, 0xb})
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:66 +0x53
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getNextGid(0xc00060c098, {0x1e5e9b0, 0xc0006a9350}, {0xc0004469e0, 0xb}, 0x1e708d0?, 0x19cf700?)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:42 +0x1fe
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).CreateVolume(0xc00060c000, {0x1e5e9b0, 0xc0006a9350}, 0xc000578620)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/controller.go:257 +0x14fe
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x1e5e9b0, 0xc0006a9350}, {0x19cb100?, 0xc000578620})
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x78
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).Run.func1({0x1e5e9b0?, 0xc0006a9350?}, {0x19cb100?, 0xc000578620?}, 0xc0006b7a50?, 0x1861ee0?)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/driver.go:101 +0x42
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x1a31640?, 0xc00060c000}, {0x1e5e9b0, 0xc0006a9350}, 0xc0005785b0, 0x1b7c558)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5680 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00061e000, {0x1e644e0, 0xc00044da00}, 0xc000494a20, 0xc0000a3200, 0x2aecc40, 0x0)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc00061e000, {0x1e644e0, 0xc00044da00}, 0xc000494a20, 0x0)
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:963 +0x28a
W1107 18:33:37.425309       1 feature_gate.go:241] Setting GA feature gate Topology=true. It will be removed in a future release.
I1107 18:33:37.425483       1 feature_gate.go:249] feature gates: &{map[Topology:true]}
I1107 18:33:37.425536       1 csi-provisioner.go:154] Version: v3.5.0
I1107 18:33:37.425578       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I1107 18:33:37.426803       1 common.go:111] Probing CSI driver for readiness
I1107 18:33:37.432065       1 csi-provisioner.go:230] Detected CSI driver efs.csi.aws.com
I1107 18:33:37.432941       1 csi-provisioner.go:302] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I1107 18:33:37.433205       1 controller.go:732] Using saving PVs to API server in background
I1107 18:33:37.433392       1 leaderelection.go:245] attempting to acquire leader lease kube-system/efs-csi-aws-com...
I1107 18:33:57.386015       1 leaderelection.go:255] successfully acquired lease kube-system/efs-csi-aws-com
I1107 18:33:57.386197       1 leader_election.go:178] became leader, starting
I1107 18:33:57.486929       1 controller.go:811] Starting provisioner controller efs.csi.aws.com_efs-csi-controller-6999bb875-k6q4s_0b7ffcb3-3d01-48cb-9afc-535c25d21738!
I1107 18:33:57.486975       1 volume_store.go:97] Starting save volume queue
I1107 18:33:57.588119       1 controller.go:1359] provision "jupyter/hub-db-dir" class "efs-dynamic": started
I1107 18:33:57.588551       1 controller.go:860] Started provisioner controller efs.csi.aws.com_efs-csi-controller-6999bb875-k6q4s_0b7ffcb3-3d01-48cb-9afc-535c25d21738!
I1107 18:33:57.589949       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"jupyter", Name:"hub-db-dir", UID:"ee583eca-b05f-4303-9eee-5135851bae0a", APIVersion:"v1", ResourceVersion:"14436", FieldPath:""}): type: 'Normal' reason:               'Provisioning' External provisioner is provisioning volume for claim "jupyter/hub-db-dir"
I1107 18:33:57.845764       1 controller.go:1082] Temporary error received, adding PVC ee583eca-b05f-4303-9eee-5135851bae0a to claims in progress
W1107 18:33:57.845780       1 controller.go:934] Retrying syncing claim "ee583eca-b05f-4303-9eee-5135851bae0a", failure 0
E1107 18:33:57.845799       1 controller.go:957] error syncing claim "ee583eca-b05f-4303-9eee-5135851bae0a": failed to provision volume with StorageClass "efs-dynamic": rpc error: code = Unavailable desc = error reading from server: EOF
I1107 18:33:57.846055       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"jupyter", Name:"hub-db-dir", UID:"ee583eca-b05f-4303-9eee-5135851bae0a", APIVersion:"v1", ResourceVersion:"14436", FieldPath:""}): type: 'Warning' reason:              'ProvisioningFailed' failed to provision volume with StorageClass "efs-dynamic": rpc error: code = Unavailable desc = error reading from server: EOF
I1107 18:33:58.845905       1 controller.go:1359] provision "jupyter/hub-db-dir" class "efs-dynamic": started
E1107 18:33:58.846070       1 connection.go:142] Lost connection to unix:///var/lib/csi/sockets/pluginproxy/csi.sock.
F1107 18:33:58.846172       1 connection.go:97] Lost connection to CSI driver, exiting
```

My storage class is pretty unremarkable and also has not been changed:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: fs-a1s2d3f4
  provisioningMode: efs-ap
  directoryPerms: "770"
  basePath: "/dynamic_provisioning"
```

If I uninstall the 2.5.0 helm chart and revert to 2.4.9, my volume provisions normally and everything works.

**Comment by bribroder** [comment] 2023-11-07 19:02
This actually seems to be a duplicate of #1164 which may be fixed on #1167

**Comment by mskanth972** [comment] 2023-11-09 04:14
Thanks all for bringing here, I added [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1180) which can solve this issue and we will merge this soon and mark in the next release.

**Comment by mskanth972** [comment] 2023-11-10 18:39
closing the issue as the latest release v1.7.1 has fixed it. Please open if you have any other issues.
/close

**Closed by mskanth972** 2023-11-10 18:39 UTC
Labels: kind/bug
