### ISSUE TITLE
Can't mount EFS to a pod: AccessPointAlreadyExists

### ISSUE THREAD

**Issue by ig-leonov** [kubernetes-sigs/aws-efs-csi-driver#1225] opened 2023-12-28 14:48 UTC
After upgrade the driver version from 1.5.5 to 1.7.0 we started to see some pods failed to mount EFS with exception like:
`I1227 14:23:13.534226       1 event.go:298] Event(v1.ObjectReference{Kind:""PersistentVolumeClaim"", Namespace:""_NAMESPACE_"", Name:""_NAME_"", UID:""60171e27-5916-44a7-a8f2-a93deed684f6"", APIVersion:""v1"", ResourceVersion:""4119172"", FieldPath:""""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass ""_SC_NAME_HERE_"": rpc error: code = Internal desc = Failed to create Access point in File System _FS_ID_HERE_ : Failed to create access point: AccessPointAlreadyExists: `

This is happening during high load (we may have hundreds of pods starting simultaneously), and efs csi driver logs mostly contain Throttling exceptions. We're using Dynamic Provisioning so access points are created and deleted by efs driver.

Attaching logs from csi provisioner for specific pvc and efs csi driver for the same timeframe:

[csi_provisioner_logs.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13787309/csi_provisioner_logs.txt)
[efs_csi_driver_logs.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13787310/efs_csi_driver_logs.txt)

This issue is not reproducible in v1.5.5, and we suspect that https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/850/commits may be one of the things that is causing it (increasing the amount of requests for DescribeAccessPoint).

Other things I think may be useful:

- this warning looks weird:
  `W1227 14:19:14.769663       1 gid_allocator.go:93] Requested GID range (50000:7000000) exceeds EFS Access Point limit (1000) per Filesystem. Driver will not allocate GIDs outside of this limit.`
 given that we  use default GID range.
- We noticed that Access Points created for these PVCs are not automatically deleted with associated PVC 

**Environment**
- Kubernetes version v1.26.10-eks-4f4795d:
- Driver version: 1.7.0

**Comment by otorreno** [comment] 2023-12-29 21:29
I have opened #1226 to reduce the number of API calls. Not sure by how much is going to help as the ListAccessPoints call is going to be there. But I am getting rid of the DescribeFileSystem call in the dynamic provisioning case.

I have fixed the warning about the requested GID range exceeding the APs limit

**Comment by otorreno** [comment] 2023-12-30 08:12
Looks like the problem is a combination of the leaked access points because of the throttling exceptions while calling the EFS API and what is getting fixed in #1217 (the call to list access points missing a parameter to list up to 1000 access points, and the default being just 100).

It seems that merging both should bring the driver to a better state

**Comment by mskanth972** [comment] 2024-01-05 20:59
closing the issue as we released the latest driver v1.7.3 with the fix.
/close

**Closed by mskanth972** 2024-01-05 20:59 UTC
