### ISSUE TITLE
Chart Version 1.2.4 Doesnt appear published

### ISSUE THREAD

**Issue by jseiser** [kubernetes-sigs/aws-efs-csi-driver#421] opened 2021-04-22 17:49 UTC
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/Chart.yaml

version: 1.2.4

```
COMBINED OUTPUT:
  ********************
  	Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: Error: failed to download "aws-efs-csi-driver/aws-efs-csi-driver" at version "1.2.4" (hint: running `helm repo update` may help)
  Error: plugin "diff" exited with error
```

**Comment by jseiser** [comment] 2021-04-22 18:19
This ends up making the documentation not quite right, since the IRSA configuration makes it appear like you can tag the resources, but the current version of the chart doesnt send those tags and you get permissions denied.

**Comment by wongma7** [comment] 2021-04-22 18:48
Yes, sorry about that, the change was merged to master branch recently but not released yet. When released there will be a git tag and associated GItHub release. To test  it out you'll have to clone the master branch and helm install ./charts/aws-efs-csi-driver.

What documentation do you mean, the values.yaml?

**Comment by jseiser** [comment] 2021-04-22 18:51
Correct.


You discussions like this:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/347

And examples: 

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json


none of these work, since it doesnt appear the currently published version of the chart, actually configured the tags.

**Comment by wongma7** [comment] 2021-04-22 18:54
Yeah, let me sort it out before the next release, probably we need this refactor https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/406.

basically the issue is that our chart is ambiguous as to whether certain values apply to the node component (daemonset) or controller component (deployment). The controller component was added later. They each need a different set of permission , the node needs the access point mount perms and the controller the tag creation and access point creation perms, but the helm chart wiring is not in a good state and needs fixing.

**Comment by wongma7** [comment] 2021-04-29 20:10
to be clear I mean the tags fixes, the other stuff regarding IAM, the PR didn't merge yet

**Closed** 2021-04-29 20:10 UTC
