### ISSUE TITLE
Unexplained api.github.com calles from aws-efs-csi-driver 

### ISSUE THREAD

**Issue by AhmadMasryCarta** [kubernetes-sigs/aws-efs-csi-driver#1271] opened 2024-02-14 18:47 UTC
/kind bug

**What happened?**
We use AWS EKS, and we use the aws-efs-csi-driver addon "Not self deployed"
Suddenly, our CI system started to fail because of 403 errors on github public apis.
After enabling Datadog Network Performance Monitoring, we discovered that the mentioned version, "v1.7.4-eksbuild.1" is doing too much calls to api.github.com without any explanation or custom configuration from our side, as we install the addon with its defaults.
Downgrading to v1.7.3-eksbuild.1 fixed the issue. so I suppose it is a dependency issue.

**What you expected to happen?**
I don't see why the addon is calling github, so it just should not call it.

**How to reproduce it (as minimally and precisely as possible)?**
Install aws-efs-csi-driver addon version v1.7.4-eksbuild.1

**Environment**
- Kubernetes version (use `kubectl version`): v1.29.0-eks-c417bb3
- Driver version: v1.7.4-eksbuild.1

Unfortunately I can't collect logs as this will affect our CI again while I am doing the troubleshooting procedure.

Thank you

**Comment by seanzatzdev-amazon** [comment] 2024-02-14 20:01
Thank you for raising this issue, we are actively working to push out driver v1.7.6 to address this. This is caused by an efs-utils v1.35.1 version check feature. We are upgrading efs-utils to disable this & will be pushing out the new driver release once that is complete.

**Comment by seanzatzdev-amazon** [comment] 2024-03-01 21:31
This has been fixed in v1.7.6 of the driver

**Closed** 2024-03-01 21:31 UTC
Labels: kind/bug
