### ISSUE TITLE
Missing permission in the example IAM policy file

### ISSUE THREAD

**Issue by foreignmeloman** [kubernetes-sigs/aws-efs-csi-driver#489] opened 2021-06-10 22:46 UTC
/kind bug

**What happened?**
Attaching [provided](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) IAM policy example to an EC2 instance did not grant enough permissions for it to mount the EFS and create a PV.
Instead the pod reported the following error:
```
Output: Failed to resolve "fs-bdfc7009.efs.us-east-1.amazonaws.com". The file system mount target ip address cannot be found, please pass mount target ip address via mount options. 
User: arn:aws:sts::888888888888:assumed-role/LordOfTheVolumes/i-0dc4f12f9fdb8dcd3 is not authorized to perform: elasticfilesystem:DescribeMountTargets on the specified resource
```

**What you expected to happen?**
I expected the provisioner to create a PV for the pod.

**How to reproduce it (as minimally and precisely as possible)?**
Just use the current version of [docs/iam-policy-example.json](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) with [examples/kubernetes/dynamic_provisioning](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/dynamic_provisioning).

**Anything else we need to know?**:
I've actually found the solution but will leave it for the maintainer to commit as I am too lazy to sign the CLA.
The error message above actually gives the solution. The first object of  the "Statement" list should look like this:

```json
        {
            "Effect": "Allow",
            "Action": [
                "elasticfilesystem:DescribeAccessPoints",
                "elasticfilesystem:DescribeFileSystems",
                "elasticfilesystem:DescribeMountTargets"
            ],
            "Resource": "*"
        },
```
After I made this change to the policy the dunamic provisioning started to work as expected.

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.3

**Comment by Karthik-13** [comment] 2021-06-28 07:38
Hi, we are facing this issue as well. 
The node daemonset also doesn't have service account attached to it. And the IAM permissions mentioned above seem to be required by the daemonset pods. 

Any update on when this issue will be fixed?

**Comment by irl-segfault** [comment] 2021-07-19 07:20
this is a major issue...as in, following the *default* AWS instructions leads to EFS CSI driver not working.  This should be fixed yesterday.

**Comment by smythie86** [comment] 2021-07-30 17:08
also ran into this issue, it made the installation process much more difficult to work through these issues until I eventually found this bug.

**Comment by kevinglasson** [comment] 2021-08-04 13:59
I also had to add `ec2:DescribeAvailabilityZones`

**Comment by bmelanson** [comment] 2021-09-03 14:33
Based on the issue description and the comments above ( https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/489#issuecomment-892682895 and https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/489#issuecomment-869449047 ) 

I found another solution is to make a new policy and service account, and be sure to attach that to the node when installing/updating the helm chart. Otherwise, my AccessDenied was from the Node role, and not the pod role.

Then in the helm command, override BOTH the controller and node service accounts:
```
helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver \
    --set controller.serviceAccount.create=false \
    --set controller.serviceAccount.name=efs-csi-controller-sa \
    --set node.serviceAccount.create=false \
    --set node.serviceAccount.name=efs-csi-node-sa
```

[iam-policy-node.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/7106585/iam-policy-node.txt)

**Comment by JaeguKim** [comment] 2021-09-08 07:54
In my case, I met the error when I set wrong file system id which  in ```values.yaml```. I recommend you to check the file system id you assigned again.

**Comment by ipleten** [comment] 2021-09-11 02:24
> In my case, I met the error when I set wrong file system id in `values.yaml`. I recommend you to check the file system id you assigned again.

What do you mean by "system id"?

**Comment by JaeguKim** [comment] 2021-09-11 07:48
> > In my case, I met the error when I set wrong file system id in `values.yaml`. I recommend you to check the file system id you assigned again.
> 
> What do you mean by "file system id" in which values.yaml?

I meant [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/a78c87199798ef68a3250635fc167a504c5f2de5/charts/aws-efs-csi-driver/values.yaml#L131).

**Comment by ipleten** [comment] 2021-09-12 03:30
Oh yeah I assumed you meant storageclass.
In my case, I suspect that kube2iam (which we have installed to support services from self-hosted k8s during migration to EKS) intercepts IRSA requests to sts and forces to assume nodes role which doesn't have permissions to do 'elasticfilesystem:DescribeMountTargets'.

**Comment by ipleten** [comment] 2021-09-14 00:38
Nodes do need to have  ''elasticfilesystem:DescribeMountTargets' and '"ec2:DescribeAvailabilityZones"'

**Comment by 0xlen** [comment] 2022-02-09 14:51
Correct me if I am wrong. EFS CSI driver is based on efs-utils to perform EFS mounting action. I reviewed the code and my understanding is that it will use DescribeMountTargets to retrieve private IP as fallback if the DNS name of EFS resource failed to resolve [1].

Perhaps the root cause was relating to EFS mount target is not in the same Availability Zone as the client instance (your pods), which are both mentioning in document [2] and [3]:

> DNS resolution for file system DNS names requires that the Amazon EFS file system has a mount target in the same Availability Zone as the client instance.

Otherwise I guess it might be relating to DNS resolution on Kubernetes (e.g. CoreDNS), intermittent resolution error, or Pod has own [DNS config](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) cause the EFS mount point DNS name did not correctly propagate to the EFS CSI driver client.

[1] https://github.com/aws/efs-utils/blob/a63e2170f7d1cdaa836cf5e79ef0eccf408f2b92/src/mount_efs/__init__.py#L2146-L2186
[2] Troubleshooting Mount Issues - File System Mount Using DNS Name Fails - https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html#mount-fails-dns-name
[3] Mounting on Amazon EC2 with a DNS name - https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html

**Comment by AndrewFarley** [comment] 2022-03-22 22:30
This just wasted hours of my team's time for a lack of documentation update.  I've submitted an documentation update above.  https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/647  Please approve, merge and close this issue finally.

**Comment by AndrewFarley** [comment] 2022-04-06 01:34
Fixed in the merge just now #647, please close this?

**Closed** 2022-04-07 09:55 UTC
Labels: kind/bug

**Comment by vmga-crisnevares** [comment] 2022-05-25 20:37
@AndrewFarley This has been fixed in the master branch, but none of the subsequent releases ([v1.3.8](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.3.8/docs/iam-policy-example.json), [helm-chart-aws-efs-csi-driver-2.2.6](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.2.6/docs/iam-policy-example.json)) include this fix.

_(Sorry, I know this probably shouldn't be directed at you, but I wasn't sure who to @)_

**Comment by BloodyIron** [comment] 2022-11-01 18:26
I am having DNS resolution for the FQDN for the EFS mount point, and I can't for the life of me find why. The relevant Role has all the appropriate permissions, as outlined here, and AWS documentation ( https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html ).

We're using EFS as a CSI driver, and the CSI driver and various components are installed via YAML manifest via Flux (as our current CD tool), not helm or anything like that.

The Role in AWS looks to have the correct policy attached, the policy looks correctly configured, the service account in k8s looks to exist in the cluster AND have the correct ARN attached for the relevant Role, the OIDC endpoint declared looks correct, the EFS is in the same AZ and subnet as the k8s cluster nodes, the VPC has DNS resolution enabled, the PV and PVC exist in the cluster, but the pod just fails to resolve the FQDN and want the IP instead.

I feel like I'm missing something stupidly small but I can't fucking find it. I've re-read the AWS official documentation like 65,536 times, looked for typos everywhere with ctrl+f comparisons, and I can't find what I'm doing wrong.

None of the troubleshooting steps (for DNS resolution failure) from AWS improve the situation ( https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html ).

It should _just work_ but... it doesn't... and argh.

**Comment by BloodyIron** [comment] 2022-11-01 22:08
The solution is that I was missing this storageClass ( https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/encryption_in_transit/specs/storageclass.yaml )

The reason I was unsure that the storageClass was a "requirement" (for TLS encryption for EFS interfacing???) was because these examples didn't declare a storageClass, but other examples did, so it felt like it was "optional":

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/specs/claim.yaml

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/specs/pv.yaml

Whereas these examples DID mention a storageClass:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/encryption_in_transit/specs/pv.yaml

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/encryption_in_transit/specs/claim.yaml

===

As such I didn't know if I _NEEDED_ the storageClass since I didn't yet know if I cared about EFS encryption-in-transit as this was a) testing and b) all within our VPC and such, so I was unsure if we cared about it.

I don't really understand why this storageClass is just not consistently a requirement between both scenarios, to avoid this uncertainty, but here we are... This appears to have solved it for me, adding the storageClass. ARGH.

**Comment by AndrewFarley** [comment] 2022-11-02 19:15
@BloodyIron Perhaps submit a bug (or PR) improving the documentation to suggest/request the end user adds a StorageClass.  To me, as a Kubernetes geek, in general, I know that any storage controller added into Kubernetes would require adding a storage class.  But, I can see this not necessarily being obvious.

**Comment by BloodyIron** [comment] 2022-11-02 20:56
Actually I want to reel back my reply a bit. I am not 100% sure if the missing storageClass was problematic.

I am however 100% certain I was in error as the EFS I had made was tied to only one AZ (it was in "One AZ" mode and not "Standard" aka multi-AZ mode) and did not realise I needed the EFS to be reachable by multiple AZ's. Remaking that EFS to be reachable by multiple AZ's did the trick. That's 100% PEBKAC on me, even though I re-read connectivity aspects many times over. Am still human!

As for the documentation, I have already submitted a bug report on clarifying the storageClass aspect due to the above weirdness between encrypted/not documentation. I really wanted to post it here for other humans to see.

**Comment by mattj150** [comment] 2022-11-07 19:05
@BloodyIron I just wanted to leave a note that your last post saved me countless hours of troubleshooting. I was running into the same issue and it indeed has something to with the EFS being in Single vs Multiple AZ mode. I had the exact same config in the same VPCs with the same AZs and the single AZ EFS would not work. Switching to multi AZ EFS solved the problem.

**Comment by BloodyIron** [comment] 2022-11-07 23:33
> @BloodyIron I just wanted to leave a note that your last post saved me countless hours of troubleshooting. I was running into the same issue and it indeed has something to with the EFS being in Single vs Multiple AZ mode. I had the exact same config in the same VPCs with the same AZs and the single AZ EFS would not work. Switching to multi AZ EFS solved the problem.

haha yay! And this is the textbook reason why I post such messages! So things I find (even by my own mistake) can help others! I'm really glad it helped you :) Yay! :D warm vibes your way my friend.

**Comment by batman1754** [comment] 2022-11-25 19:24
> In my case, creating a policy that only contains DescribeMountTargets and DescribeAvailabilityZones, and attaching that newly created policy to the node group role was sufficient to fix the issue.

@fptiangco you saved my day, thanks a lot for sharing this. i have attached the iam policy (AmazonEKS_EFS_CSI_Driver_Policy) to my eks node group role. that did the trick

**Comment by batman1754** [comment] 2022-11-25 19:48
> Nodes do need to have ''elasticfilesystem:DescribeMountTargets" and "ec2:DescribeAvailabilityZones"

Yes correct, this resolved my issue as well. @ipleten
