### ISSUE TITLE
chown/chgrp on dynamic provisioned pvc fails

### ISSUE THREAD

**Issue by gazal-k** [kubernetes-sigs/aws-efs-csi-driver#300] opened 2021-01-11 23:11 UTC
/kind bug

**What happened?**

Using dynamic provisioning feature introduced by #274 with applications that try to `chown` their pv fails.

**What you expected to happen?**

With the old [efs-provisioner](https://github.com/kubernetes-retired/external-storage/tree/master/aws/efs), this caused no issues.
But with dynamic provisioning in this csi driver, the chown command fails. I must admit, I don't understand how the uid/gid thing works with EFS access points. The pod user does not seem to have any association with the uid/gid on the access point, however pods can read & write mounted pv just fine.

**How to reproduce it (as minimally and precisely as possible)?**

- Use the dynamic provisioning feature introuduced by #274
- Create a storageClasss:
  ```yaml
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: efs-sc
  mountOptions:
  - tls
  parameters:
    directoryPerms: "700"
    fileSystemId: fs-<id>
    provisioningMode: efs-ap
  provisioner: efs.csi.aws.com
  ```
- Use it with application charts that have a chown step in the beginning, like:
  - https://github.com/grafana/helm-charts/blob/8dfa6da2790911ee78e2c9cf62f950f20e4a8129/charts/grafana/templates/_pod.tpl#L22-L40
  - https://github.com/jenkins-x-charts/nexus/blob/f05c2172a550c6bf3daf2c25eef940e67290d346/Dockerfile#L9-L10

For the first chart, we saw the initContainer failing. We just tried disabling the initContainer on the grafana chart with these chart overrides:
```yaml
initChownData:
  enabled: false
```
And the application worked fine.

For the nexus chart, there's a whole bunch of errors from the logs,

```sh
chgrp: changing group of '/nexus-data/elasticsearch/nexus': Operation not permitted
```

Perhaps these charts don't really need that step with dynamic provisioning. Another nexus chart seems to have an option to skip the `chown` step; https://github.com/travelaudience/docker-nexus/blob/a86261e35734ae514c0236e8f371402e2ea0feec/run#L3-L6

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
  ```sh
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Driver version:
  ```
  amazon/aws-efs-csi-driver:master
  quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
  k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
  ```

**Comment by gabegorelick** [comment] 2021-03-30 16:51
I'm also seeing this. This means that things like postgres, which fails to start if its data directory is not owned by the `postgres` user, don't work with dynamic provisioning. 

From https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-nfs-permissions.html,

> By default, root squashing is disabled on EFS file systems. Amazon EFS behaves like a Linux NFS server with no_root_squash. If a user or group ID is 0, Amazon EFS treats that user as the root user, and bypasses permissions checks (allowing access and modification to all file system objects). Root squashing can be enabled on a client connection when the AWS Identity and Access Management (AWS IAM) identity or resource policy does not allow access to the ClientRootAccess action. When root squashing is enabled, the root user is converted to a user with limited permissions on the NFS server.

I can reproduce this without a file system policy, and with a file system policy that grants `elasticfilesystem:ClientRootAccess`, it doesn't seem to make a difference. Granting `elasticfilesystem:ClientRootAccess` to the driver and pod's roles also doesn't help.

**Comment by wochanda** [comment] 2021-04-22 14:51
Thanks for reporting this. We're investigating possible fixes, but in the meantime let me explain the reason this is happening. 

Dynamic provisioning shares a single file system among multiple PVs by using EFS Access Points. The way Access Points work is they allow server-side overwrites of user/group information, overriding whatever the user/group of the app/container is. When we create an AP with dynamic provisioning we allocate a unique UID/GID (for instance 50000:50000) to overwrite all operations to, and create a unique directory (e.g. /ap50000) that is owned by that user/group. This ensures that no matter how the container is configured it has read/write access to its root directory. 

What is happening in this case is the application is trying to take its own steps to make its root directory writeable. For instance, if in the container there is an application user with UID/GID 100:100, when it does a ls -la on its FS root directory it sees that it is owned by 50000:50000, not 100:100, so it assumes it needs to do a chown/chmod for it to work. However, even if we allowed this command to go through the application would lose access to its own volume.

This is why the original issue above was resolved by disabling the chown/chgrp checks. This method can be used as a workaround for any application, since you can trust the PVs to be writeable out of box.

**Comment by gabegorelick** [comment] 2021-04-22 15:04
> This is why the original issue above was resolved by disabling the chown/chgrp checks. This method can be used as a workaround for any application

Some applications don't support disabling ownership checks. E.g. I'm not aware of any way to disable it in Postgres. In such cases, the only workaround I've found is to create a user for the UID assigned by the driver (something like `useradd --uid "$(stat -c '%u' "$mountpath")"`) and then run the application as that user.

**Comment by wongma7** [comment] 2021-04-22 21:58
Part of the reason efs-provisioner worked seamlessly is it relied on a beta annotation "pv.beta.kubernetes.io/gid" https://github.com/kubernetes-retired/external-storage/blob/201f40d78a9d3fd57d8a441cfc326988d88f35ec/nfs/pkg/volume/provision.go#L62 that silently does basically what your workaround does: it ensures that the Pod using the PV has the annotated group in its supplemental groups (i.e. if the annotation says '100' and you execute `groups` as the pod user, '100' will be among them)

This feature is very old and predates the rigorous KEP/feature tracking system that exists today, and I think it's been forgotten by sig-storage. Certainly i am culpable for relying on it but doing nothing to make it more than a beta annotation, I'll try to bring it up in isg-storage and see if we can rely on it as an alternative solution.

**Comment by gabegorelick** [comment] 2021-04-23 15:30
> Part of the reason efs-provisioner worked seamlessly is it relied on a beta annotation "pv.beta.kubernetes.io/gid" https://github.com/kubernetes-retired/external-storage/blob/201f40d78a9d3fd57d8a441cfc326988d88f35ec/nfs/pkg/volume/provision.go#L62 that silently does basically what your workaround does: it ensures that the Pod using the PV has the annotated group in its supplemental groups 

Does EFS still reject the chown call when using efs-provisioner, or is it that applications are expected not to call `chown` since their group already owns the directory?

If I'm reading the [Postgres code](https://github.com/postgres/postgres/blob/c30f54ad732ca5c8762bb68bbe0f51de9137dd72/src/backend/utils/init/miscinit.c#L331-L347) correctly, it seems to check the UID of the directory. So I'm not sure supplemental groups would work for all use cases.

**Comment by wongma7** [comment] 2021-04-23 19:05
> Does EFS still reject the chown call when using efs-provisioner, or is it that applications are expected not to call `chown` since their group already owns the directory?

It's the latter, so you are right, the supplemental group approach won't work in postgres case.

Does a subdirectory of the access point have the same restriction on chown'ing? If not, I suppose one could create the subdirectory before starting the applicatoin, maybe with an initContainer, and then let the application chown it. Still not a very elegant workaround tho.

**Comment by ankitbansal-gc** [comment] 2021-09-07 10:15
Can someone please suggest a workaround for postgres chown issue when using EFS with dynamic provisioning via access points?

**Comment by ankitbansal-gc** [comment] 2021-09-07 12:06
> > This is why the original issue above was resolved by disabling the chown/chgrp checks. This method can be used as a workaround for any application
> 
> Some applications don't support disabling ownership checks. E.g. I'm not aware of any way to disable it in Postgres. In such cases, the only workaround I've found is to create a user for the UID assigned by the driver (something like `useradd --uid "$(stat -c '%u' "$mountpath")"`) and then run the application as that user.

@gabegorelick - if I setup runAsUser and runAsGroup in pod security context then postgres pod fails with a FATAL error

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2021-09-07 11:06:38.315 UTC [68] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
2021-09-07 11:06:38.315 UTC [68] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
running bootstrap script ...
```

Here is the kubernetes manifest I am using

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: crm
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: pwd
  # Volume Claim
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
```

**Comment by gazal-k** [comment] 2021-09-07 12:29
This issue probably needs to be addressed, but I'm not sure about using EFS for postgres. I have seen less demanding storage use cases where EFS struggles.

**Comment by gabegorelick** [comment] 2021-09-07 14:56
> Can someone please suggest a workaround for postgres chown issue when using EFS with dynamic provisioning via access points? 

I used https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/434. That's still not merged though, so you'll have to run a fork if you want it. But that is the only way that I'm aware of to specify a UID for the provisioned volumes.

> if I setup runAsUser and runAsGroup in pod security context then postgres pod fails with a FATAL error

One workaround is to not do this. Instead, use `runAsUser: 0` and `fsGroup: 0`. Then in your container's entrypoint, invoke postgres (or whatever process you want to run) as the UID of the dynamic volume.

**Comment by ankitbansal-gc** [comment] 2021-09-07 16:03
> One workaround is to not do this. Instead, use `runAsUser: 0` and `fsGroup: 0`. Then in your container's entrypoint, invoke postgres (or whatever process you want to run) as the UID of the dynamic volume.

@gabegorelick can you please guide me on what do I nee dto change the entrypoint command from postgres to?

**Comment by wernich-vg** [comment] 2021-09-28 08:36
I see the PR fixing this is still not merged. I'm not running postgres but trying to run freshclam with EFS storage for the signatures database. In the [entrypoint](https://github.com/Cisco-Talos/clamav/blob/c389dfa4c3af92b006ada4f7595bbc3e6df3f356/dockerfiles/docker-entrypoint.sh#L18) they `chown` the database directory with no prior checks or options to overload.

**Comment by nickperkins** [comment] 2021-09-29 06:54
I would love to see this Pr merged in. Currently hitting this issue while trying to run docker:dind with a pv

**Comment by raghulkrishna** [comment] 2021-09-30 06:28
i am also having same issue with some of my applications

**Comment by svaranasi-traderev** [comment] 2021-11-10 03:53
When is this going to be fixed? I see no issues creating and mounting APs with the proper UID/GUIDs but this driver doesn't seem to respect what I pass as SC params.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: aws-efs-csi-driver
    meta.helm.sh/release-namespace: aws-efs-csi
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: efs-csi-app-sc
parameters:
  basePath: /csi
  directoryPerms: "2771"
  uid: "0"
  gid: "40055"
  fileSystemId: fs-blablabl
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Gives me this in AWS: 
![image](https://user-images.githubusercontent.com/45045920/141046725-fa5cb553-6c41-4754-8c13-98abffc9275b.png)

And an even weirder result on the pod (notice GUID):
![image](https://user-images.githubusercontent.com/45045920/141046824-531a392d-e354-435a-a416-1f0edad8ea7e.png)

This driver is messed up on so many levels.

**Comment by kergon** [comment] 2021-12-02 17:00
We've hit this attempting to run a mailer in a container. If everything was set up correctly, the code would never need to call chown() so a quick workaround (to avoid patching and recompiling) was to nuke the calls to chown()/fchown() to return 0.  

Method 1 - LD_PRELOAD (using gcc):

#include <unistd.h>
int chown(const char *path, uid_t owner, gid_t group) { return 0; }
int fchown(int fd, uid_t owner, gid_t group) { return 0;} 
gcc -c exim_chown.c; gcc -shared -o libeximchown.so exim_chown.o 
LD_PRELOAD=/tmp/libeximchown.so /usr/sbin/exim ...
(must not be setuid)

Method 2 - patch (x86) object directly (using objdump):

https://gist.github.com/shaded-enmity/b8fd0dc883e3c26681c4fe9f32c9493d
$ ./ret0.sh libpostfix-util.so chown fchown
Patching chown@plt at offset 48800 in libpostfix-util.so
Patching fchown@plt at offset 52096 in libpostfix-util.so

I would hope that this problem can be handled with a high priority by the platform, without expecting every application that might want to use the system to review and if need be change its code.  If, as this issue suggests, multiple applications are failing because the platform doesn't adhere to the traditional expectations of how unix users and groups work, how many more problems must still lie undiscovered?

**Comment by kergon** [comment] 2021-12-02 17:48
So if I read this rightly #434 (merged) will allow the uid and gid values to be squashed to preferred values, and if these are set to match the user/group that is running, when new files are created they will appear with the user/group that created them and this should avoid typical logic deciding it needs to use chown.

The second question is: What is the right behaviour for chown in such an envionment?  Should it fail if the requested state doesn't match the current state (because the user and group are fixed and can't be changed)?  Should it always succeed (because the process will have access to the file regardless of the displayed user/group)?   Or should that decision be another parameter so that the person setting this up can choose which of those two options is right for them?

**Comment by eechava66** [comment] 2022-01-14 16:01
> Gives me this in AWS: ![141046725-fa5cb553-6c41-4754-8c13-98abffc9275b](https://user-images.githubusercontent.com/45045920/141046962-e7985ce8-28de-411f-8233-f5580655585a.png)
> 
> And an even weirder result on the pod (notice GUID): ![image](https://user-images.githubusercontent.com/45045920/141046824-531a392d-e354-435a-a416-1f0edad8ea7e.png)
> 
> This driver is messed up on so many levels.

This is because the current helm chart installs the 1.3.5 version which hasn't included the configuration for GID and UID yet, in order to use that, make sure that you override the image tag value with the "master" tag that enabled this parameters. 

You can override this value in the values.yaml file as following:
```
nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: amazon/aws-efs-csi-driver
  tag: "master"  ## here!!
  pullPolicy: IfNotPresent
...
```
or  with the helm command
```
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver --set image.tag="master"
```

to check what version are running your pods, just 
```
kubectl describe pods -n kube-system efs-csi-controller-{....} | grep Image
```

**Comment by Jasper-Ben** [comment] 2022-01-24 13:30
> Even with `master` or the latest release (`1.3.6`), setting the AP to `0:0`, a simple `chown -R root:root /path` as uid `0`, still gives:
> 
> ```
> chown: /mountpath: Operation not permitted
> ```
> 
> id
> 
> ```
> uid=0(root) gid=0(root) groups=0(root)
> ```
> 
> Like @svaranasi-traderev said; this driver seems to be very messed up and AWS doesn't seem to care at all.

Noteworthy however:

When setting `uid` and `gid` to `0` (root) and then creating a new file within the mountpath as any other user than root (this will chown the file to 0:0, as described in  https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/618), this arbitrary user can then successfully run a chown on this file, which would not work if uid is set to anything other than `0`.

This leads me to believe, that **any** FS operation on this mountpath is executed as the AP user, regardless of the current active user.
Again, don't understand the magic behind this yet, so this conclusion might be obvious to others :sweat_smile:. Is this default behavior when setting a user for an NFS mount?

**Comment by sbkg0002** [comment] 2022-01-24 13:50
> When setting `uid` and `gid` to `0` (root) and then creating a new file within the mountpath as any other user than root (this will chown the file to 0:0, as described in #618), this arbitrary user can then successfully run a chown on this file, which would not work if uid is set to anything other than `0`.

The chown command only exits with a non-zero exitcode on Alpine Linux. Eventhough all files are already owned by uid `0`.

**Comment by Jasper-Ben** [comment] 2022-01-24 14:00
> > When setting `uid` and `gid` to `0` (root) and then creating a new file within the mountpath as any other user than root (this will chown the file to 0:0, as described in #618), this arbitrary user can then successfully run a chown on this file, which would not work if uid is set to anything other than `0`.
> 
> The chown command only exits with a non-zero exitcode on Alpine Linux. Eventhough all files are already owned by uid `0`.

What I mean is this:

1. As user `foo` I create the file `foo` within the mount path:

```
foo@nginx:/mnt$ touch foo
```
2. As `uid` and `gid` are set to `0`, this file will be owned as root (https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/618):
```
foo@nginx:/mnt$ ls -la
total 8
drwx------ 2 root root 6144 Jan 20 15:18 .
drwxr-xr-x 1 root root   51 Jan 20 14:57 ..
-rw-r--r-- 1 root root    0 Jan 20 15:18 foo
```
3. As user `foo` run `chown foo:foo foo`. This will succeed. It will **not** succeed if `uid` (and `gid`) is set to anything other than `0`.

Thus the chown command seems to actually run as the AP user, not as the current active user.

**Comment by pkit** [comment] 2022-01-25 13:31
@Jasper-Ben 
> Again, don't understand the magic behind this yet, so this conclusion might be obvious to others sweat_smile. Is this default behavior when setting a user for an NFS mount?

Yup, it's kinda expected for a `root_squash` NFS mount.
It can be cleanly amended with `setfacl` for a "real" NFS 
```shell
setfacl -m u:user:rwx dir
setfacl -m g:group:rwx dir
setfacl -m d:u:user:rwx dir
setfacl -m d:g:group:rwx dir
``` 
but (obviously) EFS does not support ACLs...

**Comment by jsalatiel** [comment] 2022-01-29 11:42
Why can't the AP just be created with root_no_squash?

**Comment by pkit** [comment] 2022-01-29 12:37
I don't think it works for EFS.

**Comment by Jasper-Ben** [comment] 2022-01-29 14:03
According to the docs EFS does?
https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-nfs-permissions.html#accessing-fs-nfs-permissions-root-user

**Comment by pkit** [comment] 2022-01-29 14:21
@Jasper-Ben yup, not for AP

**Comment by Jasper-Ben** [comment] 2022-01-29 17:41
So if I understand this correctly, the issue lies within enforcing a user identity for the access point:

> When user enforcement is enabled, Amazon EFS replaces the NFS client's user and group IDs with the identity configured on the access point for all file system operations. User enforcement also does the following:
>
> - **The owner and group for new files and directories are set to the user ID and group ID of the access point.**
> - EFS considers the user ID, group ID, and secondary group IDs of the access point when evaluating file system permissions. EFS ignores the NFS client's IDs.

-- https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html#enforce-identity-access-points

The efs-csi-driver currently depends on this user identity enforcement, as to ensure that rw access to the sub-folder is available:
> When we create an AP with dynamic provisioning we allocate a unique UID/GID (for instance 50000:50000) to overwrite all operations to, and create a unique directory (e.g. /ap50000) that is owned by that user/group. This ensures that no matter how the container is configured it has read/write access to its root directory.

So basically, for this issue to be resolved the driver would have to refrain from using user enforcement. I believe this could be done by using 777 permissions on the unique directories (obviously, the uniqueness would have to come from somewhere else). This might sound like a bad idea at first, giving any user within the container write access to the directory. But that's actually already the case due to the user enforcement ("EFS ignores the NFS client's IDs", as I have also shown in https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/618#issue-1109453888).

**Comment by pkit** [comment] 2022-01-29 18:08
> So basically, for this issue to be resolved the driver would have to refrain from using user enforcement. I believe this could be done by using 777 permissions on the unique directories (obviously, the uniqueness would have to come from somewhere else). This might sound like a bad idea at first, giving any user within the container write access to the directory.

You will need to alter umask too as any non-777 dir inside the root-dir will still have same problems.

I think a better workaround would be to use an application-specific StorageVolume definition with a proper uid/gid

**Comment by codelang1** [comment] 2022-03-13 09:38
Observed the same issue on Redis docker container running on k8s.

kubectl logs -f   -n sophos-cnf cnf-redis-node-0  -c volume-permissions
chown: changing ownership of '/data': Operation not permitted

Let me know if more details are needed.

**Comment by ktaletsk** [comment] 2022-03-18 22:18
@pkit's workaround helped me to run bitanmi/postgres chart (it requires uid:gid=1001:1001) without modifications just by creating a new storageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgr-efs
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: 700
  fileSystemId: fs-xxxxxxxxxxxxxxxxx
  provisioningMode: efs-ap
  gid=1001
  uid: 1001
```
and specifying this storageClass `--set global.storageClass=postgr-efs`

Related issues:
https://github.com/bitnami/charts/issues/8753
https://github.com/bitnami/bitnami-docker-postgresql/issues/184

**Comment by uclaeaslam** [comment] 2022-05-04 01:21
I would also like this fixed. Was using the old [efs-provisioner](https://github.com/kubernetes-retired/external-storage/tree/master/aws/efs) and trying to upgrade to this. I'm running the standard [wordpress](https://hub.docker.com/_/wordpress) containers, which does some chmod/chgrp at the beginning for stuff in `wp-content` folder, which will fail as everyone else above describes.

For now, able to work around it with @ktaletsk's suggestion by setting uid/guid to 33 on the storage class

**Comment by pranavgaikwad** [comment] 2022-05-10 19:08
@wochanda any reason why the driver cant make UID/GID enforcement optional just like it is in AWS console?

**Comment by lintong** [comment] 2022-07-26 12:53
> I would love to see this Pr merged in. Currently hitting this issue while trying to run docker:dind with a pv

I see the same issue in my stack @nickperkins

**Comment by kaiknight** [comment] 2022-12-26 04:23
Hi, any progress for the fix of this issue please. We're not able to deploy a procured software on EKS with EFS due to this issue. We cannot remove chown command from installation script of the software. We cannot apply the workaround suggested above to pre-configure the UID/GID, since multiple UID/GID are specified for different sub-directories in the installation script of the software.

**Comment by pkit** [comment] 2022-12-26 12:54
@kaiknight you can change chown command to be a noop for the duration of the install script. Or give it any other behavior. Just change it to your own binary that does what you need.

**Comment by kaiknight** [comment] 2023-01-03 04:44
@pkit I don't think I fully understand this workaround. If chown command, for example to set ownership to user 1001, is changed to do nothing, when files is written to subdirectories on behalf of 1001, the write behavior will fail. This will stop the installed software running. Is it correct?

**Comment by pkit** [comment] 2023-01-03 05:23
@kaiknight You can configure EFS volume with any UID/GID combination you need.
Then chown can be changed to noop.
Unless you need multiple UID/GID combinations on the same EFS volume - it will work fine.

**Comment by kaiknight** [comment] 2023-01-03 05:28
@pkit Thank you. I understand now. We could preconfigure UID/GID of the whole EFS volume to a specific user/group, we tried actually, but the problem in our case is the software to be installed requires 2 different UID for 2 different sub-directories. Setting the EFS volume to one preconfigured UID cannot resolve our problem. Still stuck in this issue.
I noticed this issue was raised two years ago (Jan-2021), does it mean there is no plan to resolve it.

**Comment by pkit** [comment] 2023-01-03 05:31
@kaiknight Unfortunately it looks like it's an AWS problem within EFS implementation. So, it won't be solved soon...or maybe ever.

**Comment by Jasper-Ben** [comment] 2023-01-03 10:54
@kaiknight take a look at https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner which you can use in combination with AWS EFS. Isn't as "clean" as using a CSI driver, but will resolve your permission issue, which seems to be a dealbreaker in your use case.

**Comment by jglick** [comment] 2023-01-05 15:49
I ran into this issue trying to run `docker:dind` as a `StatefulSet` on EKS using a `StorageClass` with no special settings (just the suggested `directoryPerms: "700"`). Similarly to https://github.com/ContainX/docker-volume-netshare/issues/94:

```
could not create or set daemon root permissions: /var/lib/docker: chown /var/lib/docker: operation not permitted
```

The error is from https://github.com/moby/moby/blob/v20.10.19/daemon/daemon_unix.go#L1223 which I traced to https://github.com/moby/moby/blob/v20.10.19/pkg/idtools/idtools_unix.go#L217-L219 and unfortunately in this case there does not appear to be any option to suppress the `chown`.

**Comment by jsalatiel** [comment] 2023-01-05 16:06
Unbelievable how hard is to aws fix this.

**Comment by pkit** [comment] 2023-01-05 16:15
@jglick 
> unfortunately in this case there does not appear to be any option to suppress the chown

There is, reading the code: `if os.FileMode(stat.Mode()).Perm() != mode.Perm() {` means that it won't run chown if directory already exists and owned by the needed user. I.e. pre-creating `/var/lib/docker` should help

**Comment by jglick** [comment] 2023-01-05 19:16
(That line of code skips the `Chmod`. The `Chown` is run unless the UID & GID align, a couple lines down.)

Anyway, that is the point of this issue as I understand it: the directory _does_ already exist by the time the pod runs, but is owned by user 50001 or whatever, as would any freshly created subdirectories (for example from an init container). This image wants to be run as UID 0 but it expects to have a directory apparently owned by UID 0, which it cannot. If the app were patched to bypass the `setPermissions` call, everything would presumably be fine.

I ran out of patience in this case, but I suppose the workaround would be to create a distinct `StorageClass` configured as UID/GID 0.

If you were running a dynamically linked app (which `dockerd` is not) perhaps you could write something like https://github.com/AaltoSciComp/teflon to make https://man7.org/linux/man-pages/man2/chown.2.html to quietly return 0 after printing a warning to stderr, either unconditionally or for files which appear to be on an NFS mount or within some designated prefix.

**Comment by pkit** [comment] 2023-01-05 19:55
@jglick 
> If you were running a dynamically linked app (which dockerd is not)

It is dynamically linked:
```
 $ ldd `which dockerd`
	linux-vdso.so.1 (0x00007ffdd7edb000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f7c4e4f9000)
	libdevmapper.so.1.02.1 => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 (0x00007f7c4e48c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7c49c00000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f7c4e481000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f7c49eb7000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7c4e454000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f7c49e08000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f7c4e434000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7c4e5e4000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f7c49bd2000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f7c49ba7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7c49abe000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f7c49a98000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f7c499fd000)
```
The problem is that it's written in go, which means it avoids using libc for posix calls.
It uses syscalls into linux directly.
Case in point `chown`: https://github.com/golang/go/blob/58f6022eee95f43b4e0dc640b012bb3f574898f1/src/cmd/vendor/golang.org/x/sys/unix/zsyscall_linux.go#L696
```
func Fchownat(dirfd int, path string, uid int, gid int, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, _, e1 := Syscall6(SYS_FCHOWNAT, uintptr(dirfd), uintptr(unsafe.Pointer(_p0)), uintptr(uid), uintptr(gid), uintptr(flags), 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
```
Which is a little harder to intercept, but still possible:
- set up prtacer
- set up bpf filter on syscalls you need: `__NR_fchownat` as that's the only syscall that golang uses
- fork the target process

See some examples here: https://github.com/alfonsosanchezbeato/ptrace-redirect/blob/master/redir_filter.c

**Comment by jglick** [comment] 2023-01-05 21:08
> It is dynamically linked

Maybe some versions; not the one in `docker:20.10.19-dind`.

At any rate, it does not sound straightforward to intercept `chown` in a typical pod on EKS.

**Comment by srudin** [comment] 2023-03-09 04:32
How can this be closed? I understand there are not enough resources to work on it now but it seems quite severe so it ought to be kept in the backlog rather than just be closed.
And considering the feedback it would probably make sense to assign it a higher priority and use some of the available resources to actually solve it.

**Closed** 2023-06-22 14:14 UTC
Labels: kind/bug, lifecycle/rotten

**Comment by z0rc** [comment] 2023-06-22 15:01
I hate this bot.

/reopen
/remove-lifecycle rotten

**Comment by lotyp** [comment] 2023-09-25 12:01
So? Any solution? I can't install rancher monitoring, which uses grafana and persistence stack on EFS, because of this error

**Comment by jetndra** [comment] 2024-01-18 07:23
please reopen it as still facing same issue efs,

**Comment by DylanWard14** [comment] 2024-02-05 01:33
> please reopen it as still facing same issue efs,

Did you find a solution, I am running into this issue also

**Comment by gazal-k** [comment] 2024-02-05 02:31
For anybody else facing this issue, please see [this comment](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300#issuecomment-824911126) to understand why this is happening.

The EFS CSI driver does implement the storage interface itself quite well. It's just that some applications expect to be able to then run commands like `chown` on the PV, which are not supported. Making such steps optional is one way to avoid application failure when using this driver. e.g.: https://github.com/jenkins-x-charts/nexus/pull/65.

**Comment by armhart** [comment] 2024-06-28 12:37
Using a fixed groupid works for me:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1202#issuecomment-2196811473

**Comment by jetndra** [comment] 2024-08-09 12:35
> @jetndra
> 
> > please reopen it as still facing same issue efs,
> 
> Did you find a solution, I am running into this issue also

As of workaround works for me :
```yaml
command: ["bash", "-c"]
        args: ["usermod -u $(stat -c '%u' '/var/lib/postgresql/data')  postgres && \
                groupmod -g $(stat -c '%u' '/var/lib/postgresql/data')  postgres && \
                chown -R postgres:postgres /var/lib/postgresql && \
                /usr/local/bin/docker-entrypoint.sh postgres"]
```
